import { Client, Account, Databases, Storage } from "appwrite";

const APPWRITE_ENDPOINT: string = process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!;
const APPWRITE_PROJECT_ID: string = process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!;
const APPWRITE_DATABASE_ID: string = process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID!;
const APPWRITE_USER_COLLECTION_ID: string = process.env.EXPO_PUBLIC_APPWRITE_USER_COLLECTION_ID!;
const APPWRITE_AVATAR_BUCKETS_ID: string = process.env.EXPO_PUBLIC_APPWRITE_AVATAR_BUCKETS_ID!;
const POSTS_COLLECTION_ID: string = process.env.EXPO_PUBLIC_APPWRITE_POST_COLLECTION_ID!;
const POSTS_ASSETS_COLLECTION_ID: string = process.env.EXPO_PUBLIC_APPWRITE_POST_ASSETS_COLLECTION_ID!;
const APPWRITE_POST_ASSETS_BUCKET_ID: string = process.env.EXPO_PUBLIC_APPWRITE_POST_ASSETS_BUCKETS_ID!;
const NOTIFICATION_COLLECTION_ID: string = process.env.EXPO_PUBLIC_APPWRITE_NOTIFICATION_COLLECTION_ID!;
const ORGANIZATION_COLLECTION_ID: string = process.env.EXPO_PUBLIC_APPWRITE_ORGANIZATION_COLLECTION_ID!;

const appwriteClient = new Client()
  .setEndpoint(APPWRITE_ENDPOINT)
  .setProject(APPWRITE_PROJECT_ID);

const account = new Account(appwriteClient);
const databases = new Databases(appwriteClient);
const storage = new Storage(appwriteClient);

export {
  appwriteClient,
  account,
  databases,
  storage,
  APPWRITE_DATABASE_ID,
  APPWRITE_USER_COLLECTION_ID,
  APPWRITE_AVATAR_BUCKETS_ID,
  APPWRITE_ENDPOINT,
  APPWRITE_PROJECT_ID,
  POSTS_COLLECTION_ID,
  POSTS_ASSETS_COLLECTION_ID,
  APPWRITE_POST_ASSETS_BUCKET_ID,
  NOTIFICATION_COLLECTION_ID,
  ORGANIZATION_COLLECTION_ID
};
